enabled handling of just eight LHEScaleWeights
uhh-cms/columnflow pull request #221
Opened 2023-04-03 13:32 UTC by pkausw

The current version of the cms LHEScaleWeight producer only allows for exactly 9 weights per event. However, there are also (some) samples that only provide 8 weights (nominal weight is dropped). This leads to a break down of the murf_scale weight producer.

This small PR extends the functionality to also handle samples with only 8 LHE weights. The producer now checks for either 9 or 8 weights. If there are only 8 LHE weights, the indices for the LHE weights that are "normally" behind the nominal weight (i.e. anything after index `4`) are shifted by one to correct the mapping to the corresponding variations.

Side note: The current documentation of NanoAOD v11 does not provide anything about the order of the LHEScaleWeights. Indeed, in the [latest](https://cms-nanoaod-integration.web.cern.ch/autoDoc/NanoAODv11/2022postEE/doc_WZ_TuneCP5_13p6TeV_pythia8_Run3Summer22EENanoAODv11-126X_mcRun3_2022_realistic_postEE_v1-v1.html) version of the documentation, the LHEScaleWeight branch is completely missing from the list of available branches. Might be worthwhile to keep an eye on this.

2023-04-03 13:58 UTC, mafrahm reviewed
Looks good to me! Just one inline comment

2023-04-03 14:04 UTC, pkausw commented on columnflow/production/cms/scale.py
> +        # down by 1
Great suggestion, I commited it directly :+1:

2023-04-08 09:26 UTC, pkausw commented
@mafrahm can you give the final approval for this PR?

2023-04-08 13:02 UTC, riga requested changes
Hey there! Looks good! 🎉

Just a minor thing regarding "externalizing" the weight lookup indices (with Run 3 nano scheme in mind -.-).

2023-04-08 13:02 UTC, riga commented on columnflow/production/cms/scale.py
> +
Stray line :)

2023-04-11 10:01 UTC, pkausw commented
Thanks for your feedback @riga ! Indeed, Mathis and I were discussing whether we should already externalize and stream-line the definition of the weight indices, but in the end decided to postpone this. Your comments are of course valid, especially regarding the up-comping Run 3!

I have started to externalize the index definition of the weights. It's working for the "normal" scale weights, but I haven't tackled the envelope producer yet. It would be nice to generalize the index definition since they are the same for both producers. But I'll have to think about this for a bit. If you already have ideas how best to do this let me know!

2023-04-11 15:53 UTC, riga commented
> I have started to externalize the index definition of the weights. It's working for the "normal" scale weights, but I haven't tackled the envelope producer yet. It would be nice to generalize the index definition since they are the same for both producers. But I'll have to think about this for a bit. If you already have ideas how best to do this let me know!

I added a commit with a draft plus minor optimizations (i.e. using a plain `1` instead of `ak.ones_like` if possible and I moved the `ak.any(nominal != 1)` check to the block where this is possible) Ok like this?

Maybe @mafrahm can do the "official" signing then ;)

2023-04-11 18:46 UTC, mafrahm approved these changes
Looks good! Tests in my analysis repository were also successful!

2023-04-11 18:47 UTC, merged